package com.primeton.tcisapiwebserviceservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-11-30T17:17:22.217+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://www.primeton.com/TcisApiWebServiceService", name = "TcisApiWebServiceService")
@XmlSeeAlso({ObjectFactory.class})
public interface TcisApiWebServiceService {

    @WebMethod
    @RequestWrapper(localName = "tcisApiWebService", targetNamespace = "http://www.primeton.com/TcisApiWebServiceService", className = "com.primeton.tcisapiwebserviceservice.TcisApiWebService")
    @ResponseWrapper(localName = "tcisApiWebServiceResponse", targetNamespace = "http://www.primeton.com/TcisApiWebServiceService", className = "com.primeton.tcisapiwebserviceservice.TcisApiWebServiceResponse")
    @WebResult(name = "out1", targetNamespace = "http://www.primeton.com/TcisApiWebServiceService")
    public java.lang.String tcisApiWebService(
        @WebParam(name = "in0", targetNamespace = "http://www.primeton.com/TcisApiWebServiceService")
        java.lang.String in0
    );
}
