package com.primeton.tcisapiwebserviceservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-11-30T17:17:22.248+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "TcisApiWebServiceServiceService", 
                  wsdlLocation = "http://10.100.10.177:8080/default/TcisApiWebServiceService?wsdl",
                  targetNamespace = "http://www.primeton.com/TcisApiWebServiceService") 
public class TcisApiWebServiceServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.primeton.com/TcisApiWebServiceService", "TcisApiWebServiceServiceService");
    public final static QName TcisApiWebServiceServicePort = new QName("http://www.primeton.com/TcisApiWebServiceService", "TcisApiWebServiceServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.100.10.177:8080/default/TcisApiWebServiceService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TcisApiWebServiceServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.100.10.177:8080/default/TcisApiWebServiceService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TcisApiWebServiceServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TcisApiWebServiceServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TcisApiWebServiceServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TcisApiWebServiceServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TcisApiWebServiceServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TcisApiWebServiceServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TcisApiWebServiceService
     */
    @WebEndpoint(name = "TcisApiWebServiceServicePort")
    public TcisApiWebServiceService getTcisApiWebServiceServicePort() {
        return super.getPort(TcisApiWebServiceServicePort, TcisApiWebServiceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TcisApiWebServiceService
     */
    @WebEndpoint(name = "TcisApiWebServiceServicePort")
    public TcisApiWebServiceService getTcisApiWebServiceServicePort(WebServiceFeature... features) {
        return super.getPort(TcisApiWebServiceServicePort, TcisApiWebServiceService.class, features);
    }

}
